---
- name: Exchange Keys between servers
  hosts: temp
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id 
        creates="~/.ssh/id"

    - name: Fetch the keyfile from the node to master
      tags: run
      fetch: 
        src: "~/.ssh/id.pub"
        dest: "buffer/{{inventory_hostname}}-id.pub"
        flat: yes

    - name: Copy the key add to authorized_keys using Ansible module
      tags: runcd
      authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file','buffer/{{item}}-id.pub')}}"
      when: "{{ item != inventory_hostname }}"
      with_items: 
        - "{{ groups['temp'] }}"
